### ISSUE TITLE
compile failed: oneapi error 

### ISSUE THREAD

**Issue by TxT1212** [nmoehrle/mvs-texturing#193]
Thanks for your great work.
I try to compile in ubuntu 18.04 and have this problem:
> In file included from /home/txt/slam/mvs-texturing/elibs/mapmap/mapmap/full.h:18:0,
                 from /home/txt/slam/mvs-texturing/libs/tex/view_selection.cpp:14:
/home/txt/slam/mvs-texturing/elibs/mapmap/mapmap/header/color.h:13:10: fatal error: oneapi/tbb/concurrent_vector.h: No such file or directory
 #include <oneapi/tbb/concurrent_vector.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
libs/tex/CMakeFiles/tex.dir/build.make:367: recipe for target 'libs/tex/CMakeFiles/tex.dir/view_selection.cpp.o' failed
make[2]: *** [libs/tex/CMakeFiles/tex.dir/view_selection.cpp.o] Error 1
CMakeFiles/Makefile2:307: recipe for target 'libs/tex/CMakeFiles/tex.dir/all' failed
make[1]: *** [libs/tex/CMakeFiles/tex.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve it? Thanks.

**Comment by VisionQJ** [comment]
Did you fixed this problem, met it too @TxT1212

**Comment by TxT1212** [comment]
> Did you fixed this problem, met it too @TxT1212

Nope, for days I have been waking up in the mid of night crying

**Comment by VisionQJ** [comment]
Damn let's debug

**Comment by VisionQJ** [comment]
check Updated git tag for mapmap #192 @TxT1212

**Comment by TxT1212** [comment]
> check Updated git tag for mapmap #192 @TxT1212

thanks, it works! Now I prefer FDU to SJTU.

**Comment by CodeAunt** [comment]
@TxT1212 Hi bro, have you built this on Ubuntu18.04 successfully?

**Comment by TxT1212** [comment]
> @TxT1212 Hi bro, have you built this on Ubuntu18.04 successfully?

Yes, I have. but I've been busy with other things, haven't run it.

**Comment by CodeAunt** [comment]
@TxT1212 ok, I'll try
